### ISSUE TITLE
Waning immunity

### ISSUE THREAD

**Issue by mknaranja** [SciCompMod/memilio#205]
In order to simulate the effect of waning immunity, integro and ordinary differential equation models will have to be extended.

- [ ] For IDE models, we have to allow for reinfection or infection after vaccination
- [ ] For IDE models, we need to see how a particular age-of-recovery/-vaccination function can be added to equation for R
- [x] For ODE models, we need to discuss if additional compartments (e.g., recovery in last 3 months, recovery > 3 months ago etc.)  have to/should be added to simulate the effect of waning immunity
- [x] For ABMs, waning immunity was implemented with #389

More details to be added to the description

**Comment by xsaschako** [comment]
- [ ] For the ABM we need to have a history of vaccination and track an immunity level.

**Comment by DavidKerkmann** [comment]
> [ ] For the ABM we need to have a history of vaccination and track an immunity level.

This is considered in issue #389

**Comment by HenrZu** [comment]
For the ode models, this was adressed in Issue #323. What about the ABM @xsaschako ? If yes, we can close this issue and then move the IDE work in a IDE specific issue @annawendler ?

**Comment by DavidKerkmann** [comment]
> For the ode models, this was adressed in Issue #323. What about the ABM @xsaschako ? If yes, we can close this issue and then move the IDE work in a IDE specific issue @annawendler ?

The waning immunity in the ABM is implemented as optionals function which describe immunity as
- protection against transmission,
- protection against severe course,
- protection against high viral load.
These functions map time to a protection percentage and can basically be freely set by the user.
See also #389 as linked above.
There are certainly ways to improve this framework, but this one already gives quite some flexibility.
