### ISSUE TITLE
Configuring and Starting Simulations via a REST-Api

### ISSUE THREAD

**Issue by JonasGilg** [SciCompMod/memilio#206]
The goal is, that a service is provided, that accepts requests via a REST-Api. These requests specify the parameters for a simulation run. The simulation is then started and the result is returned to the caller.

Steps:
- [ ] Make simulations easily startable with user defined parameters
- [ ] Create a REST-Service that
  - takes requests
  - starts simulations
  - returns results
  - (maybe caches results in the database)
- [ ] Deploy this service to a machine, that can handle running simulations

One thing to consider is, that the simulations run longer and results are not available immediately. So the service needs some a way of communicating progress. A possible solution could be:
1. A request to start a simulation comes in.
2. An id is created, that references the simulation, that is about to start.
3. The id is returned to the caller.
4. The caller can send additional requests via the REST-Api using the given id to get progress updates.
5. Once the progress reaches completion the caller can create a REST-Request to fetch the results.
